# Generated by Django 5.1 on 2024-08-26 19:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paystack', '0001_initial'),
        ('sps_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bank Account Name')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('amount_available_cash', models.BigIntegerField()),
                ('amount_available_transfer', models.BigIntegerField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAccountTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'TRANSFER'), ('CASH', 'CASH')], max_length=100)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('PENDING_EDIT', 'PENDING_EDIT'), ('PENDING_DELETE', 'PENDING_DELETE'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], default='PENDING_APPROVAL', max_length=50)),
                ('transaction_category', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=50)),
                ('reason', models.TextField(null=True)),
                ('name_of_receiver', models.CharField(max_length=100)),
                ('account_number_of_receiver', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paystack.bank')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAccountTransactionModificationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50)),
                ('head_teacher_comment', models.TextField(blank=True, null=True)),
                ('date_of_modification', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_operations_account.operationsaccounttransactionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAccountTransactionRecordsEditedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state_attribute', models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_receiver', 'name_of_receiver'), ('account_number_of_receiver', 'account_number_of_receiver'), ('bank', 'bank'), ('time', 'time')], max_length=50)),
                ('previous_state_value', models.CharField(max_length=50)),
                ('new_state_attribute', models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_receiver', 'name_of_receiver'), ('account_number_of_receiver', 'account_number_of_receiver'), ('bank', 'bank'), ('time', 'time')], max_length=50)),
                ('new_state_value', models.CharField(max_length=50)),
                ('date_of_modification', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_operations_account.operationsaccounttransactionmodificationtracker')),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.AddField(
            model_name='operationsaccounttransactionrecord',
            name='particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_operations_account.particular'),
        ),
    ]
