# Generated by Django 4.2.5 on 2023-12-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_class_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniformandbooksfeecategory',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='uniformandbooksfeecategory',
            name='school',
        ),
    ]
