# Generated by Django 4.2.5 on 2024-01-08 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_remove_uniformandbooksfeecategory_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feescategory',
            name='name',
        ),
        migrations.AddField(
            model_name='otherfeecategory',
            name='term',
            field=models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], default='FIRST TERM', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='next_class_to_be_promoted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.class'),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('IN DEBT', 'IN DEBT'), ('OUTSTANDING', 'OUTSTANDING')], default='IN DEBT', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolconfig',
            name='term',
            field=models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], default='FIRST TERM', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolfeescategory',
            name='term',
            field=models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=50),
        ),
    ]
