# Generated by Django 4.2.5 on 2024-01-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_remove_feescategory_name_otherfeecategory_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feescategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.school'),
        ),
    ]
