# Generated by Django 4.2.5 on 2024-06-13 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_alter_operations_account_transaction_record_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxroll',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.school'),
        ),
    ]
