# Generated by Django 4.2.5 on 2024-08-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_taxroll_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_account', models.CharField(max_length=100)),
                ('to_account', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PENDING_EDIT', 'PENDING_EDIT'), ('PENDING_DELETE', 'PENDING_DELETE'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], default='PENDING', max_length=50),
        ),
    ]
