# Generated by Django 4.2.5 on 2024-08-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paystack', '0001_initial'),
        ('Main', '0031_receipts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations_account_transaction_modification_tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='account_number_of_reciever',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paystack.bank'),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'PENDING_APPROVAL'), ('PENDING_EDIT', 'PENDING_EDIT'), ('PENDING_DELETE', 'PENDING_DELETE'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='Operations_account_transaction_records_edited_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state_attribute', models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_reciever', 'name_of_reciever'), ('account_number_of_reciever', 'account_number_of_reciever'), ('bank', 'bank')], max_length=50)),
                ('previous_state_value', models.CharField(max_length=50)),
                ('new_state_attribute', models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_reciever', 'name_of_reciever'), ('account_number_of_reciever', 'account_number_of_reciever'), ('bank', 'bank')], max_length=50)),
                ('new_state_value', models.CharField(max_length=50)),
                ('date_of_modification', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.operations_account_transaction_modification_tracker')),
            ],
        ),
        migrations.AddField(
            model_name='operations_account_transaction_modification_tracker',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.operations_account_transaction_record'),
        ),
    ]
