# Generated by Django 4.2.5 on 2024-08-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations_account_transaction_modification_tracker',
            name='atatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='operations_account_transaction_modification_tracker',
            name='head_teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_modification_tracker',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.operations_account_transaction_record'),
        ),
    ]
