# Generated by Django 4.2.5 on 2024-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_operations_account_transaction_modification_tracker_atatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations_account_transaction_modification_tracker',
            name='atatus',
        ),
        migrations.AddField(
            model_name='operations_account_transaction_modification_tracker',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50),
        ),
    ]
