# Generated by Django 4.2.5 on 2024-08-20 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0035_remove_operations_account_transaction_modification_tracker_atatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_records_edited_fields',
            name='new_state_attribute',
            field=models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_reciever', 'name_of_reciever'), ('account_number_of_reciever', 'account_number_of_reciever'), ('bank', 'bank'), ('time', 'time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_records_edited_fields',
            name='previous_state_attribute',
            field=models.CharField(choices=[('amount', 'amount'), ('particulars', 'particulars'), ('reason', 'reason'), ('name_of_reciever', 'name_of_reciever'), ('account_number_of_reciever', 'account_number_of_reciever'), ('bank', 'bank'), ('time', 'time')], max_length=50),
        ),
    ]
