# Generated by Django 4.2.5 on 2024-08-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_alter_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations_account_transaction_modification_tracker',
            name='date_of_modification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
