# Generated by Django 5.1 on 2024-08-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('SCHOOL FEES', 'SCHOOL FEES'), ('UNIFORM WEARS AND BOOKS', 'UNIFORM WEARS AND BOOKS'), ('BUS FEES', 'BUS FEES'), ('OTHER', 'OTHER')], max_length=60)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='BusFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=50)),
                ('morning_bus_fee', models.BigIntegerField(default=0)),
                ('evening_bus_fee', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_fees_payment_structure.feescategory')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=50)),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('minimum_percentage', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_fees_payment_structure.feescategory')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time_initiated', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_email', models.EmailField(max_length=254)),
                ('amount_debited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], max_length=20)),
                ('receipt_id', models.CharField(max_length=20)),
                ('paystack_reference', models.CharField(max_length=50)),
                ('breakdowns', models.JSONField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('IN DEBT', 'IN DEBT'), ('OUTSTANDING', 'OUTSTANDING')], default='IN DEBT', max_length=50)),
                ('last_amount_paid', models.BigIntegerField(default=0)),
                ('amount_in_debt', models.BigIntegerField(default=0)),
                ('amount_outstanding', models.BigIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sps_core.student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=50)),
                ('minimum_percentage', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_fees_payment_structure.feescategory')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolLevyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.BigIntegerField(default=0, null=True)),
                ('amount_in_debt', models.BigIntegerField(default=0, null=True)),
                ('amount_outstanding', models.BigIntegerField(default=0, null=True)),
                ('percentage_paid', models.IntegerField(default=0, null=True)),
                ('percentage_of_student_in_debt', models.IntegerField(default=0, null=True)),
                ('percentage_of_student_outstanding', models.IntegerField(default=0, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='UniformAndBooksFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('is_recommended', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('minimum_percentage', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_fees_payment_structure.feescategory')),
            ],
        ),
    ]
