# Generated by Django 5.1 on 2024-08-26 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('amount_paid', models.BigIntegerField(default=0, null=True)),
                ('next_class_to_be_promoted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sps_core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], default='FIRST TERM', max_length=50)),
                ('academic_session', models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='2020/2021', max_length=50)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('salary_deduction', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('tin_number', models.CharField(max_length=50)),
                ('paystack_id', models.CharField(blank=True, max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paystack.bank')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
                ('staff_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sps_core.stafftype')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=60)),
                ('student_id', models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
    ]
