# Generated by Django 5.1 on 2024-08-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sps_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_account', models.CharField(max_length=100)),
                ('to_account', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bank Account Name')),
                ('account_number', models.CharField(max_length=100, verbose_name='Account Number')),
                ('amount_availabe', models.BigIntegerField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalAccountTransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sps_core.school')),
            ],
        ),
    ]
